Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from matplotlib import pyplot as plt
from utilities import sumarise_solph_results

fig, electricity_total = sumarise_solph_results(results)
plt.close()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[4], line 4[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mimport[39;00m pyplot [38;5;28;01mas[39;00m plt
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mutilities[39;00m [38;5;28;01mimport[39;00m sumarise_solph_results
[0;32m----> 4[0m fig, electricity_total [38;5;241m=[39m [43msumarise_solph_results[49m[43m([49m[43mresults[49m[43m)[49m
[1;32m      5[0m plt[38;5;241m.[39mclose()

File [0;32m~/work/oemof-workshop-osmses-2023/oemof-workshop-osmses-2023/workshop/model/utilities.py:114[0m, in [0;36msumarise_solph_results[0;34m(results)[0m
[1;32m    111[0m results [38;5;241m=[39m solph[38;5;241m.[39mviews[38;5;241m.[39mconvert_keys_to_strings(results)
[1;32m    113[0m heat_supply [38;5;241m=[39m results[([38;5;124m"[39m[38;5;124mheat pump[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mheat 35C[39m[38;5;124m"[39m)][[38;5;124m"[39m[38;5;124msequences[39m[38;5;124m"[39m][[38;5;124m"[39m[38;5;124mflow[39m[38;5;124m"[39m]
[0;32m--> 114[0m storage_content [38;5;241m=[39m [43mresults[49m[43m[[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mthermal storage[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mNone[39;49m[38;5;124;43m"[39;49m[43m)[49m[43m][49m[[38;5;124m"[39m[38;5;124msequences[39m[38;5;124m"[39m][[38;5;124m"[39m[38;5;124mstorage_content[39m[38;5;124m"[39m]
[1;32m    115[0m demand [38;5;241m=[39m results[([38;5;124m"[39m[38;5;124mheat 35C[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mheat demand[39m[38;5;124m"[39m)][[38;5;124m"[39m[38;5;124msequences[39m[38;5;124m"[39m][[38;5;124m"[39m[38;5;124mflow[39m[38;5;124m"[39m]
[1;32m    117[0m fig, (ax1, ax2) [38;5;241m=[39m plt[38;5;241m.[39msubplots([38;5;241m1[39m, [38;5;241m2[39m, sharey[38;5;241m=[39m[38;5;28;01mTrue[39;00m, figsize[38;5;241m=[39m([38;5;241m9[39m, [38;5;241m4.5[39m))

[0;31mKeyError[0m: ('thermal storage', 'None')
KeyError: ('thermal storage', 'None')

